OpenOrchestra\ModelInterface\Model\NodeInterface:
    constraints:
        - OpenOrchestra\BackofficeBundle\Validator\Constraints\BlockNodePattern: ~
        - OpenOrchestra\BackofficeBundle\Validator\Constraints\AuthorizeEdition: ~
        - OpenOrchestra\BackofficeBundle\Validator\Constraints\RestoreNode: { groups: [restore] }
