parameters:
    open_orchestra_workflowfunction_admin.left_panel.workflowfunction.class: OpenOrchestra\WorkflowFunctionAdminBundle\LeftPanel\Strategies\WorkflowFunctionPanelStrategy

services:
    open_orchestra_workflowfunction_admin.left_panel.workflowfunction:
        class: %open_orchestra_workflowfunction_admin.left_panel.workflowfunction.class%
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
