parameters:
    open_orchestra_workflow_function_admin.type.orchestra_workflow_function.class: OpenOrchestra\WorkflowFunctionAdminBundle\Form\Type\OrchestraWorkflowFunctionType

services:
    open_orchestra_workflow_function_admin.type.orchestra_workflow_function:
        class: %open_orchestra_workflow_function_admin.type.orchestra_workflow_function.class%
        arguments:
            - %open_orchestra_workflow_function.document.workflow_function.class%
        tags:
            - { name: form.type, alias: orchestra_workflow_function }
