parameters:
    open_orchestra_workflow_function_admin.subscriber.update_status.class: OpenOrchestra\WorkflowFunctionAdminBundle\EventSubscriber\UpdateStatusSubscriber

services:
    open_orchestra_workflow_function_admin.subscriber.update_status:
        class: %open_orchestra_workflow_function_admin.subscriber.update_status.class%
        arguments:
            - @security.context
            - @open_orchestra_model.repository.role
            - @open_orchestra_workflow_function.repository.workflow_function
        tags:
            - { name: kernel.event_subscriber }
