parameters:
    open_orchestra_workflow_function_admin.voter.workflow_right.class: OpenOrchestra\WorkflowFunctionAdminBundle\Security\Authorization\Voter\WorkflowRightVoter

services:
    open_orchestra_workflow_function_admin.voter.workflow_right:
        class: %open_orchestra_workflow_function_admin.voter.workflow_right.class%
        tags:
            - { name: security.voter }
