parameters:
    open_orchestra_workflow_function_admin.voter.workflow_right.class: OpenOrchestra\WorkflowFunctionAdminBundle\Security\Authorization\Voter\WorkflowRightVoter

services:
    open_orchestra_workflow_function_admin.voter.workflow_right:
        class: %open_orchestra_workflow_function_admin.voter.workflow_right.class%
        arguments:
            - @open_orchestra_workflow_function.repository.workflow_right
            - @open_orchestra_model.repository.content_type
        tags:
            - { name: security.voter }
