services:
    open_orchestra_log.left_panel.log:
        class: %open_orchestra_backoffice.left_panel.administration.class%
        arguments:
            - logs
            - ROLE_ACCESS_LOG
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
        calls:
            - [ setTemplate, ['OpenOrchestraLogBundle:AdministrationPanel:logs.html.twig'] ]
