parameters:
    open_orchestra_log.processor.log_user.class: OpenOrchestra\LogBundle\Processor\LogUserProcessor

services:
    open_orchestra_log.processor.log_user:
        class: %open_orchestra_log.processor.log_user.class%
        arguments:
            - @security.context
            - @request_stack
            - @open_orchestra_backoffice.context_manager
        tags:
            - { name: monolog.processor, method: processRecord, channel: openorchestra }
