parameters:
    php_orchestra_log.processor.log_user.class: PHPOrchestra\LogBundle\Processor\LogUserProcessor

services:
    php_orchestra_log.processor.log_user:
        class: %php_orchestra_log.processor.log_user.class%
        arguments:
            - @security.context
            - @request_stack
        tags:
            - { name: monolog.processor, method: processRecord, channel: phporchestra }