parameters:
    open_orchestra_backoffice.block_parameter_manager.class: OpenOrchestra\BackofficeBundle\StrategyManager\BlockParameterManager
    open_orchestra_backoffice.block_parameter.content.class: OpenOrchestra\Backoffice\BlockParameter\Strategies\ContentStrategy

services:
    open_orchestra_backoffice.block_parameter_manager:
        class: %open_orchestra_backoffice.block_parameter_manager.class%
    open_orchestra_backoffice.block_parameter.content:
        class: %open_orchestra_backoffice.block_parameter.content.class%
        tags:
            - { name: open_orchestra_backoffice.block_parameter.strategy }
