parameters:
    php_orchestra_display.display.carrousel.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\CarrouselStrategy
    php_orchestra_display.display.footer.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\FooterStrategy
    php_orchestra_display.display.menu.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\MenuStrategy
    php_orchestra_display.display.sample.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\SampleStrategy
    php_orchestra_display.display.tiny_mce_wysiwyg.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\TinyMCEWysiwygStrategy
    php_orchestra_indexation.display.search.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\SearchStrategy
    php_orchestra_indexation.display.search_result.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\SearchResultStrategy
