parameters:
    php_orchestra_backoffice.display.carrousel.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\CarrouselStrategy
    php_orchestra_backoffice.display.gallery.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\GalleryStrategy
    php_orchestra_backoffice.display.contact.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\ContactStrategy
    php_orchestra_backoffice.display.header.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\HeaderStrategy
    php_orchestra_backoffice.display.footer.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\FooterStrategy
    php_orchestra_backoffice.display.menu.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\MenuStrategy
    php_orchestra_backoffice.display.sample.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\SampleStrategy
    php_orchestra_backoffice.display.tiny_mce_wysiwyg.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\TinyMCEWysiwygStrategy
    php_orchestra_backoffice.display.configurable_content.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\ConfigurableContentStrategy
    php_orchestra_backoffice.display.search.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\SearchStrategy
    php_orchestra_backoffice.display.search_result.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\SearchResultStrategy
    php_orchestra_backoffice.display.login.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\LoginStrategy
    php_orchestra_backoffice.display.sub_menu.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\SubMenuStrategy
    php_orchestra_backoffice.display.content_list.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\ContentListStrategy
    php_orchestra_backoffice.display.media_list_by_keyword.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\MediaListByKeywordStrategy
    php_orchestra_backoffice.display.content.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\ContentStrategy
    php_orchestra_backoffice.display.language_list.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\LanguageListStrategy
    php_orchestra_backoffice.display.audience_analysis.class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\AudienceAnalysisStrategy

services:
    php_orchestra_backoffice.display.contact:
        class: %php_orchestra_backoffice.display.contact.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.footer:
        class: %php_orchestra_backoffice.display.footer.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.menu:
        class: %php_orchestra_backoffice.display.menu.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.search_result:
        class: %php_orchestra_backoffice.display.search_result.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.search:
        class: %php_orchestra_backoffice.display.search.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.login:
        class: %php_orchestra_backoffice.display.login.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.sub_menu:
        class: %php_orchestra_backoffice.display.sub_menu.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.content_list:
        class: %php_orchestra_backoffice.display.content_list.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.media_list_by_keyword:
        class: %php_orchestra_backoffice.display.media_list_by_keyword.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.content:
        class: %php_orchestra_backoffice.display.content.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.language_list:
        class: %php_orchestra_backoffice.display.language_list.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.carrousel:
        class: %php_orchestra_backoffice.display.carrousel.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.gallery:
        class: %php_orchestra_backoffice.display.gallery.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.tiny_mce_wysiwyg:
        class: %php_orchestra_backoffice.display.tiny_mce_wysiwyg.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.youtube:
        class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\YoutubeStrategy
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.dailymotion:
        class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\DailymotionStrategy
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.vimeo:
        class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\VimeoStrategy
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.gmap:
        class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\GmapStrategy
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.add_this:
        class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\AddThisStrategy
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.audience_analysis:
        class: %php_orchestra_backoffice.display.audience_analysis.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_backoffice.display.video:
        class: PHPOrchestra\BackofficeBundle\DisplayBlock\Strategies\VideoStrategy
        tags:
            - { name: php_orchestra_display.display_block.strategy }
