parameters:
    open_orchestra_backoffice.extract_reference_manager.class: OpenOrchestra\BackofficeBundle\StrategyManager\ExtractReferenceManager
    open_orchestra_backoffice.extract_reference.node.class: OpenOrchestra\Backoffice\ExtractReference\Strategies\ExtractReferenceFromNodeStrategy
    open_orchestra_backoffice.extract_reference.content.class: OpenOrchestra\Backoffice\ExtractReference\Strategies\ExtractReferenceFromContentStrategy

services:
    open_orchestra_backoffice.extract_reference_manager:
        class: %open_orchestra_backoffice.extract_reference_manager.class%
    open_orchestra_backoffice.extract_reference.node:
        class: %open_orchestra_backoffice.extract_reference.node.class%
        tags:
            - { name: open_orchestra_backoffice.extract_reference.strategy }
    open_orchestra_backoffice.extract_reference.content:
        class: %open_orchestra_backoffice.extract_reference.content.class%
        tags:
            - { name: open_orchestra_backoffice.extract_reference.strategy }

