parameters:

#--[CUSTOM FIELDS]--------------#
    open_orchestra_backoffice.field_types:
        text:
            label: open_orchestra_backoffice.form.field_type.custom_type.text
            type: text
            options:
                max_length:
                    default_value: 25
                required:
                    default_value: false
        textarea:
            label: open_orchestra_backoffice.form.field_type.custom_type.textarea
            type: textara
            options:
                max_length:
                    default_value: 100
                required:
                    default_value: false
        tinymce:
            label: open_orchestra_backoffice.form.field_type.custom_type.wysiwyg
            type: tinymce
            options:
                max_length:
                    default_value: 500
                required:
                    default_value: false
        integer:
            label: open_orchestra_backoffice.form.field_type.custom_type.integer
            type: integer
            options:
                rounding_mode:
                    default_value: 0
                grouping:
                    default_value: 0
                required:
                    default_value: false
        email:
            label: open_orchestra_backoffice.form.field_type.custom_type.email
            type: email
            options:
                max_length:
                    default_value: 50
                required:
                    default_value: false
        orchestra_media:
            label: open_orchestra_backoffice.form.field_type.custom_type.media
            type: orchestra_media
            options:
                required:
                    default_value: false
        choice:
            label: open_orchestra_backoffice.form.field_type.custom_type.choice
            options:
                required:
                    default_value: false
                multiple:
                    default_value: false
                expanded:
                    default_value: false
                choices:
                    default_value: null
        money:
            label: open_orchestra_backoffice.form.field_type.custom_type.money
            options:
                required:
                    default_value: false
                currency:
                    default_value: EUR
                precision:
                    default_value: 2
        hidden:
            label: open_orchestra_backoffice.form.field_type.custom_type.hidden
        date:
            label: open_orchestra_backoffice.form.field_type.custom_type.date
            options:
                required:
                    default_value: false
                format:
                    default_value: dd-MM-yyyy
                widget:
                    default_value: choice
                input:
                    default_value: array

    open_orchestra_backoffice.options:
        max_length:
            type: integer
            label: open_orchestra_backoffice.form.orchestra_fields.max_length
            required: true
        required:
            type: checkbox
            label: open_orchestra_backoffice.form.orchestra_fields.required_field
            required: false
        grouping:
            type: integer
            label: open_orchestra_backoffice.form.orchestra_fields.format
            required: true
        rounding_mode:
            type: integer
            label: open_orchestra_backoffice.form.orchestra_fields.rounding_mode
            required: true
        multiple:
            type: checkbox
            label: open_orchestra_backoffice.form.orchestra_fields.multiple
            required: false
        expanded:
            type: checkbox
            label: open_orchestra_backoffice.form.orchestra_fields.expanded
            required: false
        choices:
            type: orchestra_choices_option
            label: open_orchestra_backoffice.form.orchestra_fields.choices
            required: true
        currency:
            type: text
            label: open_orchestra_backoffice.form.orchestra_fields.currency
            required: true
        precision:
            type: integer
            label: open_orchestra_backoffice.form.orchestra_fields.precision
            required: true
        format:
            type: text
            label: open_orchestra_backoffice.form.orchestra_fields.date_format
            required: true
        widget:
            type: orchestra_date_widget_option
            label: open_orchestra_backoffice.form.orchestra_fields.widget
            required: true
        input:
            type: hidden
            label: open_orchestra_backoffice.form.orchestra_fields.date_format
            required: true
