parameters:
    php_orchestra_backoffice.type.node.class: PHPOrchestra\BackofficeBundle\Form\Type\NodeType

services:
    # Node form type
    php_orchestra_backoffice.type.node:
        class: %php_orchestra_backoffice.type.node.class%
        arguments:
            - @router
            - %php_orchestra_model.document.node.class%
        tags:
            - { name: form.type, alias: node }
