parameters:
    open_orchestra_user.repository.group.class: OpenOrchestra\UserBundle\Repository\GroupRepository

services:
    open_orchestra_user.repository.group:
        class: %open_orchestra_user.repository.group.class%
        factory:
            - @doctrine.odm.mongodb.document_manager
            - getRepository
        calls:
            - [setAggregationQueryBuilder, [@doctrine_mongodb.odm.default_aggregation_query]]
        arguments:
            - %open_orchestra_user.document.group.class%
