parameters:
    open_orchestra_user.repository.group.class: OpenOrchestra\UserBundle\Repository\GroupRepository

services:
    open_orchestra_user.repository.group:
        class: %open_orchestra_user.repository.group.class%
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getRepository
        arguments:
            - %open_orchestra_user.document.group.class%
