parameters:
    open_orchestra_backoffice.subscriber.update_child_node_path.class: OpenOrchestra\BackofficeBundle\EventSubscriber\UpdateChildNodePathSubscriber
    open_orchestra_backoffice.subscriber.update_media_reference.class: OpenOrchestra\BackofficeBundle\EventSubscriber\UpdateMediaReferenceSubscriber
    open_orchestra_backoffice.subscriber.update_node_redirection.class: OpenOrchestra\BackofficeBundle\EventSubscriber\UpdateNodeRedirectionSubscriber
    open_orchestra_backoffice.subscriber.flush_node_clache.class: OpenOrchestra\BackofficeBundle\EventSubscriber\FlushNodeCacheSubscriber
    open_orchestra_backoffice.subscriber.change_content_status.class: OpenOrchestra\BackofficeBundle\EventSubscriber\ChangeContentStatusSubscriber
    open_orchestra_media.subscriber.media_cache__invalidate.class: OpenOrchestra\BackofficeBundle\EventSubscriber\MediaChacheInvalidateSubscriber

services:
    open_orchestra_backoffice.subscriber.update_child_node_path:
        class: %open_orchestra_backoffice.subscriber.update_child_node_path.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @service_container
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.update_media_reference:
        class: %open_orchestra_backoffice.subscriber.update_media_reference.class%
        arguments:
            - @open_orchestra_backoffice.extract_reference_manager
            - @open_orchestra_media.repository.media
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.update_node_redirection:
        class: %open_orchestra_backoffice.subscriber.update_node_redirection.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @open_orchestra_backoffice.manager.redirection
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.flush_node_clache:
        class: %open_orchestra_backoffice.subscriber.flush_node_clache.class%
        arguments:
            - @open_orchestra_display.manager.cacheable
            - @open_orchestra_base.manager.tag
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.change_content_status:
        class: %open_orchestra_backoffice.subscriber.change_content_status.class%
        arguments:
            - @open_orchestra_display.manager.cacheable
            - @open_orchestra_base.manager.tag
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_media.subscriber.media_cache_invalidate:
        class: %open_orchestra_media.subscriber.media_cache__invalidate.class%
        arguments:
            - @open_orchestra_display.manager.cacheable
            - @open_orchestra_base.manager.tag
        tags:
            - { name: kernel.event_subscriber }
