parameters:
    open_orchestra_backoffice.subscriber.update_child_node_path.class: OpenOrchestra\BackofficeBundle\EventSubscriber\UpdateChildNodePathSubscriber
    open_orchestra_backoffice.subscriber.update_media_reference.class: OpenOrchestra\BackofficeBundle\EventSubscriber\UpdateMediaReferenceSubscriber
    open_orchestra_backoffice.subscriber.update_node_redirection.class: OpenOrchestra\BackofficeBundle\EventSubscriber\UpdateNodeRedirectionSubscriber
    open_orchestra_backoffice.subscriber.publish_node.class: OpenOrchestra\BackofficeBundle\EventSubscriber\PublishNodeSubscriber

services:
    open_orchestra_backoffice.subscriber.update_child_node_path:
        class: %open_orchestra_backoffice.subscriber.update_child_node_path.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @service_container
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.update_media_reference:
        class: %open_orchestra_backoffice.subscriber.update_media_reference.class%
        arguments:
            - @open_orchestra_backoffice.extract_reference_manager
            - @open_orchestra_media.repository.media
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.update_node_redirection:
        class: %open_orchestra_backoffice.subscriber.update_node_redirection.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @open_orchestra_backoffice.manager.redirection
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_backoffice.subscriber.publish_node:
        class: %open_orchestra_backoffice.subscriber.publish_node.class%
        arguments:
            - @open_orchestra_display.manager.cacheable
        tags:
            - { name: kernel.event_subscriber }
