parameters:
    php_orchestra_backoffice.transformer.embedkeywords_to_keywords.class: PHPOrchestra\BackofficeBundle\Form\DataTransformer\EmbedKeywordsToKeywordsTransformer

services:
    php_orchestra_backoffice.transformer.embedkeywords_to_keywords:
        class: %php_orchestra_backoffice.transformer.embedkeywords_to_keywords.class%
        arguments:
            - @php_orchestra_model.repository.keyword
            - %php_orchestra_model.document.embed_keyword.class%
            - %php_orchestra_model.document.keyword.class%
