parameters:
    open_orchestra_backoffice.twig_extension.translation_choice.class: OpenOrchestra\BackofficeBundle\Twig\TranslationChoiceExtension
    open_orchestra_backoffice.twig_extension.is_folder_deletable.class: OpenOrchestra\BackofficeBundle\Twig\IsFolderDeletableExtension
    open_orchestra_backoffice.twig_extension.block_icon.class: OpenOrchestra\BackofficeBundle\Twig\BlockIconExtension
    open_orchestra_backoffice.twig_extension.left_panel.class: OpenOrchestra\BackofficeBundle\Twig\LeftPanelExtension

services:
    open_orchestra_backoffice.twig_extension.translation_choice:
        class: %open_orchestra_backoffice.twig_extension.translation_choice.class%
        arguments:
            - @open_orchestra_backoffice.manager.translation_choice
        tags:
            - { name: twig.extension}
    open_orchestra_backoffice.twig_extension.is_folder_deletable:
        class: %open_orchestra_backoffice.twig_extension.is_folder_deletable.class%
        arguments:
            - @open_orchestra_backoffice.manager.media_folder
        tags:
            - { name: twig.extension}
    open_orchestra_backoffice.twig_extension.block_icon:
        class: %open_orchestra_backoffice.twig_extension.block_icon.class%
        arguments:
            - @open_orchestra_backoffice.display_icon_manager
        tags:
            - { name: twig.extension}
    open_orchestra_backoffice.twig_extension.left_panel:
        class: %open_orchestra_backoffice.twig_extension.left_panel.class%
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }
