parameters:
    open_orchestra_model.validatorcontent_template.class: OpenOrchestra\BackofficeBundle\Validator\Constraints\ContentTemplateValidator
    open_orchestra_model.validator.block_node_pattern.class: OpenOrchestra\BackofficeBundle\Validator\Constraints\BlockNodePatternValidator

services:
    open_orchestra_model.validatorcontent_template:
        class: %open_orchestra_model.validatorcontent_template.class%
        arguments:
            - @twig
        tags:
            - { name: validator.constraint_validator, alias: content_template}
    open_orchestra_model.validator.block_node_pattern:
        class: %open_orchestra_model.validator.block_node_pattern.class%
        arguments:
            - @open_orchestra_backoffice.generate_form_manager
            - @session
            - @templating
            - @translator
        tags:
            - { name: validator.constraint_validator, alias: block_node_pattern}
