OpenOrchestra\BackofficeBundle\Form\Type\TinymceType:
    properties:
        contentTemplate:
            - OpenOrchestra\BackOfficeBundle\Validator\Constraints\ContentTemplate: ~
OpenOrchestra\UserBundle\Document\ApiClient:
    properties:
        name:
            - NotBlank: ~
