parameters:

#--[CUSTOM FIELDS]--------------#
    
    php_orchestra_cms.custom_types:
        
        text:
            label: text
            options:
                max_length:
                    type: integer
                    label: php_orchestra_cms.orchestra_fields.max_length
                    default_value: 0
                    required: true
                required:
                    type: checkbox
                    label: php_orchestra_cms.orchestra_fields.required_field
                    default_value: false
                    required: false
        
        textarea:
            label: textarea
            options:
                max_length:
                    type: integer
                    label: php_orchestra_cms.orchestra_fields.max_length
                    default_value: 0
                    required: true
                required:
                    type: checkbox
                    label: php_orchestra_cms.orchestra_fields.required_field
                    default_value: false
                    required: false
        
        integer:
            label: integer
            options:
                rounding_mode:
                    type: integer
                    label: php_orchestra_cms.orchestra_fields.rounding_mode
                    default_value: 0
                    required: true
                grouping:
                    type: integer
                    label: php_orchestra_cms.orchestra_fields.format
                    default_value: 0
                    required: true
                required:
                    type: checkbox
                    label: php_orchestra_cms.orchestra_fields.required_field
                    default_value: false
                    required: false
        
        email:
            label: email
            options:
                max_length:
                    type: integer
                    label: php_orchestra_cms.orchestra_fields.max_length
                    default_value: 0
                    required: true
                required:
                    type: checkbox
                    label: php_orchestra_cms.orchestra_fields.required_field
                    default_value: false
                    required: false
        
