php_orchestra_cms_bo:
    pattern: /admin
    defaults: { _controller: PHPOrchestraCMSBundle:BackOfficeView/BackOffice:home }

php_orchestra_cms_bo_edito:
    pattern: /edito
    defaults: { _controller: PHPOrchestraCMSBundle:BackOfficeView/BackOffice:edito }

php_orchestra_cms_bo_jscontextmenudispatcher:
    pattern: /admin/js-menu-dispatcher/{cmd}
    defaults: { _controller: PHPOrchestraCMSBundle:BackOfficeView/BackOffice:jsContextMenuDispatch, cmd: '' }
