parameters:
    php_orchestra_cms.manager.context.class : 'PHPOrchestra\CMSBundle\Context\ContextManager'
    php_orchestra_cms.type.multilingual_text.class : 'PHPOrchestra\CMSBundle\Form\Type\MultilingualTextType'
    php_orchestra_cms.type.content_type_fields.class : 'PHPOrchestra\CMSBundle\Form\Type\ContentTypeFieldsType'
    php_orchestra_cms.type.custom_field.class : 'PHPOrchestra\CMSBundle\Form\Type\CustomFieldType'

services:

#--[FORM FIELDS]----------------#

    # Multilingual text field
    php_orchestra_cms.type.multilingual_text:
        class: "%php_orchestra_cms.type.multilingual_text.class%"
        arguments: ["%php_orchestra_base.languages_availables%"]
        tags: [{name: form.type, alias: multilingualText}]

    # Content type fields
    php_orchestra_cms.type.content_type_fields:
        class: "%php_orchestra_cms.type.content_type_fields.class%"
        tags: [{name: form.type, alias: content_type_fields}]

    # Custom field
    php_orchestra_cms.type.custom_field:
        class: "%php_orchestra_cms.type.custom_field.class%"
        arguments: ["%php_orchestra_cms.custom_types%"]
        tags: [{name: form.type, alias: orchestra_customField}]
