parameters:
    open_orchestra_media_admin.left_panel.folder.class: OpenOrchestra\MediaAdminBundle\LeftPanel\Strategies\TreeFolderPanelStrategy

services:
    open_orchestra_media_admin.left_panel.folder:
        class: %open_orchestra_media_admin.left_panel.folder.class%
        arguments:
            - @open_orchestra_media.repository.media_folder
            - @open_orchestra_backoffice.context_manager
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }
