parameters:
    open_orchestra_media_admin.subscriber.update_media_reference.class: OpenOrchestra\MediaAdminBundle\EventSubscriber\UpdateMediaReferenceSubscriber
    open_orchestra_media_admin.subscriber.media_cache_invalidate.class: OpenOrchestra\MediaAdminBundle\EventSubscriber\MediaChacheInvalidateSubscriber

services:
    open_orchestra_media_admin.subscriber.update_media_reference:
        class: %open_orchestra_media_admin.subscriber.update_media_reference.class%
        arguments:
            - @open_orchestra_media_admin.extract_reference_manager
            - @open_orchestra_media.repository.media
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_media_admin.subscriber.media_cache_invalidate:
        class: %open_orchestra_media_admin.subscriber.media_cache_invalidate.class%
        arguments:
            - @open_orchestra_display.manager.cacheable
            - @open_orchestra_base.manager.tag
        tags:
            - { name: kernel.event_subscriber }
