parameters:
#    php_orchestra_user.example.class: PHPOrchestra\UserBundle\Example

services:
#    php_orchestra_user.example:
#        class: %php_orchestra_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
