parameters:
    php_orchestra_user.repository.user.class: PHPOrchestra\UserBundle\Repository\UserRepository

services:
    php_orchestra_user.repository.user:
        class: %php_orchestra_user.repository.user.class%
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getRepository
        arguments:
            - PHPOrchestra\UserBundle\Document\User
