parameters:
    open_orchestra_workflowfonction_admin.transformer.workflowfonction_collection.class: OpenOrchestra\WorkflowFonctionAdminBundle\Transformer\WorkflowFonctionCollectionTransformer
    open_orchestra_workflowfonction_admin.transformer.workflowfonction.class: OpenOrchestra\WorkflowFonctionAdminBundle\Transformer\WorkflowFonctionTransformer

services:
    open_orchestra_workflowfonction_admin.transformer.workflowfonction_collection:
        class: %open_orchestra_workflowfonction_admin.transformer.workflowfonction_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_workflowfonction_admin.transformer.log:
        class: %open_orchestra_workflowfonction_admin.transformer.workflowfonction.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
