parameters:
    open_orchestra_api.security.authentication_provider.oauth2.class: OpenOrchestra\ApiBundle\Security\Authentication\Provider\OAuth2AuthenticationProvider
    open_orchestra_api.security.listener.oauth2.class: OpenOrchestra\ApiBundle\Security\Firewall\OAuth2Listener

services:
    open_orchestra_api.security.authentication_provider.oauth2:
        class: %open_orchestra_api.security.authentication_provider.oauth2.class%
        arguments:
            - @open_orchestra_user.repository.access_token
    open_orchestra_api.security.listener.oauth2:
        class: %open_orchestra_api.security.listener.oauth2.class%
        arguments:
            - @security.context
            - @security.authentication.manager
