parameters:
    open_orchestra_user_admin.transformer.user.class: OpenOrchestra\UserAdminBundle\Transformer\UserTransformer
    open_orchestra_user_admin.transformer.user_collection.class: OpenOrchestra\UserAdminBundle\Transformer\UserCollectionTransformer

services:
    open_orchestra_user_admin.transformer.user:
        class: %open_orchestra_user_admin.transformer.user.class%
        arguments:
            - @event_dispatcher
            - @open_orchestra_backoffice.manager.translation_choice
            - @security.authorization_checker
        tags:
            - { name: open_orchestra_api.transformer.strategy}
    open_orchestra_user_admin.transformer.user_collection:
        class: %open_orchestra_user_admin.transformer.user_collection.class%
        arguments:
            - @security.authorization_checker
        tags:
            - { name: open_orchestra_api.transformer.strategy}
